name: CI

on: [push]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Get golangci
        run: |
          # Add go binaries to GOPATH.
          # FIX: https://github.com/actions/setup-go/issues/14
          export PATH=${PATH}:`go env GOPATH`/bin
          go get -u github.com/golangci/golangci-lint/...
      - uses: actions/checkout@v1
      - name: check
        run: |
          # Add go binaries to GOPATH.
          # FIX: https://github.com/actions/setup-go/issues/14
          export PATH=${PATH}:`go env GOPATH`/bin
          make ci-check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - run: make ci-test

  release-image:
    if: startsWith(github.ref, 'refs/tags/') && contains(github.ref, 'master')
    env:
      TAG_IMAGE_LATEST: true
      PROD_IMAGE_NAME: ${GITHUB_REPOSITORY}
      #PROD_IMAGE_NAME: docker.pkg.github.com/${GITHUB_REPOSITORY}/app
      #PROD_IMAGE_NAME: registry.gitlab.com/${GITHUB_REPOSITORY}
    needs: [check, test]
    name: Release image
    runs-on: ubuntu-latest
    # Only run in master and when has a tag.
    steps:
      - name: Set tag on VERSION env var
        run: echo ::set-env name=VERSION::$(echo ${GITHUB_REF:10})
      - uses: actions/checkout@v1
      - name: Build image
        run: make build-image
      - name: Docker login
        run: docker login ${DOCKER_HOST} -u ${DOCKER_USER} -p ${DOCKER_TOKEN}
        env:
          # DockerHub.
          DOCKER_HOST: ""
          DOCKER_USER: slok
          DOCKER_TOKEN: ${{secrets.DOCKER_HUB_TOKEN}}
          ## Github.
          # DOCKER_HOST: docker.pkg.github.com
          # DOCKER_TOKEN: ${{secrets.GITHUB_TOKEN}}
          # DOCKER_USER: ${GITHUB_ACTOR}
          ## Gitlab.
          # DOCKER_HOST: registry.gitlab.com
          # DOCKER_USER: slok
          # DOCKER_TOKEN: ${{secrets.GITLAB_TOKEN}}

      - name: Publish image
        run: make publish-image
